# Generated by Django 3.2.4 on 2021-08-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PRD', 'обрабатывается'), ('PD', 'оплачен'), ('RDY', 'готов к выдаче'), ('CNC', 'отменён')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
